{% set version = "1.3" %}

package:
  name: otpmml
  version: {{ version }}

source:
  fn: otpmml-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otpmml/archive/v{{ version }}.tar.gz  # [not win]
  sha256: fdd1f253cfd2110aeaee82816103fe3cc30d72f42fea0159cf2e7c5c95eabc92  # [not win]

  fn: otpmml-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otpmml-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  sha256: 522a4f74706061257bc3ec2056381890e2c02de70a5b86426c77cf4a0b476721  # [win32 and py27]

  fn: otpmml-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otpmml-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: 3f5875f329d086078c25537014e89f5e4c34f03dde3d98f9cef2e989f2fbe33c  # [win64 and py27]

  fn: otpmml-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otpmml-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  sha256: 848a1011e59d145a46d352f3f881a9beb392ab4c87d0b2dea02324473ff36a77  # [win32 and py34]

  fn: otpmml-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otpmml-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  sha256: 17e7e7ef0849a6b8139ee65117f51788599f9fb61fb563963f0a4a2bd241b234  # [win64 and py34]

  fn: otpmml-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otpmml-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  sha256: b859324ade98c838ac8e90ed6ec1b4165a5445db4ebabbac0d4c97af0bbd9e97  # [win32 and py35]

  fn: otpmml-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otpmml-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: b11902f6de0357dbc6443d5dbf552dee1c24feec20e9534b9d255653a3667095  # [win64 and py35]

build:
  number: 3

requirements:
  build:
    - toolchain
    - python
    - cmake  # [not win]
    - swig  # [not win]
    - openturns  # [not win]

  run:
    - python
    - openturns

test:
  imports:
    - otpmml

about:
  home: http://openturns.org/
  license: LGPLv3
  license_file: COPYING.LESSER  # [not win]
  summary: Meta-modeling exchange module

extra:
  recipe-maintainers:
    - jschueller
