travis:
  secure:
    BINSTAR_TOKEN: ihMYYWhYjZbldel0yLF6RZMwDhV86z/L7QE3sAoZmIU1bguFTqgld6XhIokp4w1qnTQxn3vQ03rhvgcEJc0LuS9V0f5WFRkQFi8D0CdzHgpW3+EWER21IloYeRbMN6A5a2kV3q1X1WMk4taLaQuatvOC7caaKlZ9fd1ThqrtJJR9o2RWRII5sHTUkuuR5z+AHaug/AMBSTWZ/wpLd9CgjUfIs3b0xp8pgEVh4wYwGsVvZApds5/vbFjMGzccn89zts68VQ0eEEO+fcH3Vmuj9Mg9hfxJ8YAapQ9axjS4Ycdrsp0x9r4xqmrUSN4bjOu/BF9d5adryah29inE0pnjh39W4LB1zj4VxMOwKj7SWlJ/BEgDu7ckKv+NX8cGc1Be5yWNySV5pL6UKK/DrQVPY25XvCiujdf1qLJJEH/kQ4VFwuEJHtYrn4OKCXr1tOk8yiy2v+bUWllV6zrVkuqFIA+NjehMhjiH8GDzBZ1i4+NMmydtVTNj2Ix3UhaO6mSRiDcwKOE+WA/k13drG7kznMFHLHNqeiPmpdHTz+ETu4SYKFqjSBH7DYMaIq+p7ZW+AmNSEbqY7BxoyCmAsh8WkxInOxmz/KbjxHsQUECsMIDp3dMpIxb+pSBoJdj0J+TQBN8hLH9LV8048At0m/eNT3rV/LHwWjJ3k5QrFePly8o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
